name: flutter_deriv_api
description: Support for the deriv.com websockets API

version: 1.0.0

homepage: https://developers.binary.com
publish_to: "none"

environment:
  sdk: ">=3.0.0"
  flutter: "3.10.2"

dependencies:
  flutter:
    sdk: flutter

  deriv_dependency_injector:
    git:
      url: https://github.com/deriv-com/deriv-dependency-injector.git
      ref: master

  build: ^2.4.1
  dart_style: ^2.3.0
  equatable: ^2.0.3
  flutter_bloc: ^8.1.2
  http: ^0.13.4
  intl: ^0.18.0
  meta: ^1.8.0
  recase: ^4.0.0
  rxdart: ^0.27.7
  device_info_plus: ^8.1.0
  flutter_system_proxy:
    git:
      url: git@github.com:BrowserStackCE/flutter_system_proxy.git
      ref: main
  package_info_plus: ^4.2.0
  connectivity_plus: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  bloc_test: ^9.1.1
  code_builder: ^4.10.0
  build_config: ^1.1.1
  build_runner: ^2.4.8
  build_test: ^2.2.2
  json_schema2: ^2.0.2
  path: ^1.8.0
  test: ^1.19.5
