name: flutter_deriv_api
description: Support for the deriv.com websockets API

version: 0.0.1

homepage: https://developers.binary.com
publish_to: "none"

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ^1.10.0

dependencies:
  flutter:
    sdk: flutter

  build: ^2.0.0
  connectivity: ^3.0.3
  dart_style: ^2.0.0
  equatable: ^2.0.0
  flutter_bloc: ^7.0.0
  http: ^0.13.0
  intl: ^0.17.0-nullsafety.2
  meta: ^1.3.0
  recase: ^4.0.0-nullsafety.0
  rxdart: ^0.26.0
  web_socket_channel: ^2.0.0
  collection: ^1.15.0-nullsafety.4
  device_info: ^2.0.2
  package_info: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  bloc_test: ^8.0.0
  code_builder: ^4.1.0
  build_config: ^1.0.0
  build_runner: ^2.1.2
  build_test: ^2.0.0
  json_schema2: ^2.0.0
  path: ^1.8.0
  test: ^1.16.5

flutter:
  plugin:
    platforms:
      android:
        package: com.deriv.flutter_deriv_api
        pluginClass: FlutterDerivApiPlugin
      ios:
        pluginClass: FlutterDerivApiPlugin
