name: flutter_deriv_api
description: Support for the deriv.com websockets API
version: 0.0.1
author: binary.com <api-support@binary.com>
homepage: https://developers.binary.com

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  json_annotation: ^3.0.0
  web_socket_channel: ^1.0.15
  flutter_webview_plugin: ^0.3.8
  connectivity: ^0.4.4
  build: ^1.2.0
  build_config: ^0.4.1
  code_builder: ^3.1.1
  dart_style: ^1.0.0
  preferences: ^5.0.2
  flutter_bloc: ^3.2.0
  flutter:
    sdk: flutter

dev_dependencies:
  recase: ^2.0.1
  build_runner: ^1.0.0
  build_test: ^0.10.9+1
  json_serializable: ^3.2.2
  json_schema: ^2.2.1
  build_verify: ^1.0.0
  path: ^1.5.1
  test: ^1.6.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.deriv.flutter_deriv_api
    pluginClass: FlutterDerivApiPlugin
