name: flutter_deriv_api
description: Support for the deriv.com websockets API

version: 1.0.0

homepage: https://developers.binary.com
publish_to: "none"

environment:
  sdk: ">=3.0.0"

dependencies:
  deriv_dependency_injector:
    git:
      url: https://github.com/deriv-com/deriv-dependency-injector.git
      ref: master

  build: ^2.3.1
  dart_style: ^2.3.0
  equatable: ^2.0.3
  flutter_bloc: ^8.1.2
  http: ^0.13.4
  intl: ^0.19.0
  meta: ^1.8.0
  recase: ^4.0.0
  rxdart: ^0.27.7
  flutter_system_proxy:
    git:
      url: https://github.com/BrowserStackCE/flutter_system_proxy.git
      ref: v0.1.4
  package_info_plus: ^8.0.2
  connectivity_plus: ^5.0.2
  web_socket_channel: ^3.0.1
  device_info_plus: ^10.1.2

dev_dependencies:
  bloc_test: ^9.1.1
  code_builder: ^4.1.0
  build_config: ^1.0.0
  build_runner: ^2.3.0
  build_test: ^2.1.5
  json_schema2: ^5.1.3
  path: ^1.8.0
  test: ^1.19.5
