name: flutter_deriv_api
description: Support for the deriv.com websockets API
version: 0.0.1
homepage: https://developers.binary.com

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ^1.10.0

dependencies:
  flutter:
    sdk: flutter
  build: ^1.2.0
  build_config: ^0.4.1
  code_builder: ^3.1.1
  connectivity: ^0.4.4
  dart_style: ^1.0.0
  flutter_bloc: ^5.0.0
  flutter_webview_plugin: ^0.3.8
  json_annotation: ^3.0.0
  meta: ^1.1.8
  preferences: ^5.0.2
  web_socket_channel: ^1.0.15
  equatable: ^1.1.1
  recase: ^2.0.1
  rxdart: ^0.24.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  build_test: ^0.10.9+1
  build_verify: ^1.0.0
  json_schema: ^2.2.1
  json_serializable: ^3.2.5
  path: ^1.5.1
  test: ^1.6.0
  bloc_test: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.deriv.flutter_deriv_api
        pluginClass: FlutterDerivApiPlugin
      ios:
        pluginClass: FlutterDerivApiPlugin
