name: flutter_deriv_api
description: Support for the deriv.com websockets API

version: 0.2.0

homepage: https://developers.binary.com
publish_to: "none"

environment:
  sdk: ">=3.0.0"
  flutter: "3.10.2"

dependencies:
  flutter:
    sdk: flutter

  deriv_dependency_injector:
    git:
      url: git@github.com:regentmarkets/flutter-deriv-packages.git
      path: packages/deriv_dependency_injector
      ref: flutter-version-3

  deriv_web_socket_client:
    git:
      url: git@github.com:regentmarkets/flutter-deriv-packages.git
      path: packages/deriv_web_socket_client
      ref: 8cc61cc301f259f2debd0cace29cee79392735ef

  build: ^2.3.1
  dart_style: ^2.3.0
  equatable: ^2.0.3
  flutter_bloc: ^8.1.2
  http: ^0.13.4
  intl: ^0.18.0
  meta: ^1.8.0
  recase: ^4.0.0
  rxdart: ^0.27.7
  device_info_plus: ^8.1.0
  package_info_plus: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  bloc_test: ^9.1.1
  code_builder: ^4.1.0
  build_config: ^1.0.0
  build_runner: ^2.3.0
  build_test: ^2.1.5
  json_schema2: ^2.0.2
  path: ^1.8.0
  test: ^1.19.5

flutter:
  plugin:
    platforms:
      android:
        package: com.deriv.flutter_deriv_api
        pluginClass: FlutterDerivApiPlugin
      ios:
        pluginClass: FlutterDerivApiPlugin
